// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManager.DAL;

namespace UserManager.DAL.Migrations
{
    [DbContext(typeof(UserManagerContext))]
    [Migration("20201103113247_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("UserManager.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnName("user_name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserStatus")
                        .HasColumnName("user_status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            UserName = "tom@gmail.com",
                            UserStatus = 2
                        },
                        new
                        {
                            Id = 2,
                            UserName = "alice@yahoo.com",
                            UserStatus = 3
                        },
                        new
                        {
                            Id = 3,
                            UserName = "sam@online.com",
                            UserStatus = 4
                        },
                        new
                        {
                            Id = 4,
                            UserName = "val@online.com",
                            UserStatus = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
